Algoritmo "questao3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/12/2023
Var
cont: inteiro

Inicio

cont <- 100

enquanto (cont <= 300) faca
         se (cont % 10 <> 0) entao
            escreval(cont)
         fimse
         cont <- cont + 1
fimenquanto


Fimalgoritmo