Algoritmo "Lista05.1-Questao2"
// Desenvolver um programa que exiba os números em ordem decrescente de 100 até 1.
Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Exibindo todos os números em ordem descrescente de 100 até 1")

contador <- 100

enquanto ( contador >= 1) faca
         escreval(contador)
         contador <- contador - 1
fimenquanto


Fimalgoritmo