Algoritmo "Exemplo2"
// Pergunte um número ao usuário e informe se este número é par ou ímpar.
Var
// Seção de Declarações das variáveis 
numero: inteiro
divisao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Informe um número:")
leia (numero)

se (numero%2 =0) entao
   escreva("O número é par!")
senao
     escreva("O número é ímpar!")

fimse



Fimalgoritmo