Algoritmo "questao1"
// Desenvolver um programa que pergunte ao usuário o seu nome completo e seu
//sexo. Em seguida, o programa
//deve apresentar os dados anteriormente informados;
Var
// Seção de Declarações das variáveis 
nome, sexo: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Qual é o seu nome completo?")
leia(nome)
escreval("Qual é o seu sexo?")
leia(sexo)
escreval("Seu nome completo é: ",nome)
escreval("Seu sexo é: ",sexo)

Fimalgoritmo