Algoritmo "questao6"
// Fazer um algoritmo que peça um número, e ao final, informe se o número
// digitado está acima de 1000 ou
//abaixo de 1000.

Var
num: inteiro

Inicio
escreval("Informe um número:")
leia(num)

se num > 1000 entao
   escreval(num, " está acima de 1000!")
fimse
se num < 1000 entao
     escreval(num, " está abaixo de 1000!")
fimse
se num = 1000 entao
   escreval("O número é 1000!")
fimse

Fimalgoritmo