Algoritmo "questao1"
// Fazer um algoritmo que leia o numerador e o denominador de uma fração,
// e informe como resposta o
//número decimal correspondente a esta fração.
Var
numerador, denominador: real

Inicio
escreval("Informe um numerador de uma fração:")
leia(numerador)

escreval("Informe o denominador da fração:")
leia(denominador)

escreval("O número decimal dessa fração é: ",numerador / denominador)


Fimalgoritmo