Algoritmo "questao1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2023
Var
base, altura, perimetro: real

Inicio
escreval("Informe a base do retângulo:")
leia(base)

escreval("Informe a altura do retângulo:")
leia(altura)

perimetro <- 2 * (base + altura)

escreval("O perímetro do retângulo é:", perimetro)

Fimalgoritmo