Algoritmo "questao4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/11/2023
Var
cont: inteiro

Inicio

cont <- 300

escreval("Os números existente no intervalo de 300 a 500 são:")
enquanto (cont <= 500) faca
         escreval(cont)
           cont <- cont + 1
fimenquanto

Fimalgoritmo