Algoritmo "questao7"
// Desenvolver um programa que apresente o valor de uma potência de uma base
//qualquer elevada a um expoente
//qualquer, ou seja, de NM.

Var
base, expoente, potencia: real

Inicio
escreval("Escolha uma base de uma potência:")
leia(base)

escreval("Escolha um  número para ser o expoente da potência:")
leia(expoente)

potencia <- base ^ expoente

escreval("O valor da potência é:",potencia)


Fimalgoritmo