Algoritmo "questao2"
// Desenvolver um programa que leia um número
//e informe se ele é positivo, negativo ou nulo.
Var
num: inteiro
resto: real

Inicio
escreval("Informe um número:")
leia(num)

se (num >= 1) entao
        escreval("O número inserido é positivo")
fimse
se (num <= -1) entao
   escreval("O número inserido é negativo")
fimse
se (num = 0) entao
   escreval("O número é nulo")
fimse

Fimalgoritmo