Algoritmo "questao11"
// Desenvolver um programa que triangule uma matriz de ordem 10.
//Deverá aparecer como resposta algo assim na tela:
Var
cont, cont2: inteiro

Inicio

para cont2 de 1 ate 10 passo 1 faca
       para cont de 1 ate 10 passo 1 faca
            se cont2 < 10 entao
               escreva ( " ",cont2," -", cont, " ")
            senao
                 escreva(cont2, " -", cont, " " )
            fimse
       fimpara
 escreval()
fimpara


Fimalgoritmo